### ISSUE TITLE
Doesn’t work on NVIDIA GPUs

### ISSUE THREAD

**Issue by PPPDUD** [Manawyrm/AnotterKiosk#12]
Whenever I try to boot AnotterKiosk on any device with an NVIDIA GPU, it just hangs on a blinking white cursor on a blank, black background.

It boots just fine on non-NVIDIA GPUs, though.

**Comment by Manawyrm** [comment]
Oh, interesting! 
Yes, this was only tested with Intel & AMD so far.

What's the exact NVIDIA GPU you're trying to use?
Maybe this is a case of missing firmware for noveau (if supported).

**Comment by PPPDUD** [comment]
I'm using a custom-built PC with an NVIDIA GEFORCE RTX 2060 SUPER.
GRUB works fine, and whenever AnotterKiosk hangs on a blinking cursor, I
can see it doing a little bit of disk activity.

Whenever I press the power button, it shuts down as expected.

**Comment by Manawyrm** [comment]
Hm, interesting. I'll prepare a newer image with a more modern Linux kernel and send you the release link as soon as it's ready.

In the mean time: Are you familiar with SSH keys / can you setup AnotterKiosk with the authorized_keys file, so you can log onto the Kiosk with another computer? This way, we could look at the log files / error messages. 😄 

Adding Nvidia support might be a bit tricky, the newest Nvidia GPU I currently have available is a GTX750 (and that works).

**Comment by Manawyrm** [comment]
@PPPDUD OK, I've released AnotterKiosk v0.3.0, which now contains Linux 6.5. With any luck, it has better Nvidia compatibility.

Please give it a shot: https://github.com/Manawyrm/AnotterKiosk/releases/tag/v0.3.0

**Comment by PPPDUD** [comment]
Okay! I'll give it a shot!

**Comment by PPPDUD** [comment]
Update: Now, it's saying `[FAILED] Failed to start lightdm.service - Light
Display Manager`.

**Comment by PPPDUD** [comment]
Update: Still getting a blinking cursor. One time, it gave me a LightDM error, but most of the time it's just the blinking cursor.

**Comment by Manawyrm** [comment]
> One time, it gave me a LightDM error

Ah, good info. I've prepared another release. Will send you the link as soon as it's ready.

**Comment by Manawyrm** [comment]
https://github.com/Manawyrm/AnotterKiosk/releases/tag/v0.3.1

I've added a Xorg module for noveau (the open Nvidia driver).
Try that image, it might have a better chance of working :)

**Comment by PPPDUD** [comment]
I will soon!

**Comment by PPPDUD** [comment]
I tested it on the same computer as before, and it's still hanging on the
blinking cursor.

**Comment by Manawyrm** [comment]
Dang... Then we're kinda out of luck.

To do any further troubleshooting we'd need to get some logfiles, which means you'd need to setup SSH.
If you've never done this, it might be a bit hard to do.

Want to continue troubleshooting this? What's your main PCs OS?

**Comment by PPPDUD** [comment]
My main PC runs Windows 11, and I've never used SSH before.

I would be willing to do a bit more debugging work with you.

**Comment by Manawyrm** [comment]
Check you this tutorial, then: 
https://upcloud.com/resources/tutorials/generating-and-using-ssh-keys-with-putty

and generate an SSH key for your PC.
Put the storage medium with AnotterKiosk back into your PC and create a new text file called "authorized_keys" with a text editor (notepad, sublime text, vs code, something like that, not word) and put the stuff from PuttyGen in there. 
Save the key file to your PC, double click it to load it. If you're doing other Linux stuff later, it's useful to have, maybe check out how this works anyway, it's good for security! 

Boot that AnotterKiosk media again and then you need to go to your routers webinterface and try to find out which IP address your AnotterKiosk got. Hopefully it's visible somewhere.

Then you can use Putty (instead of Puttygen), set it to "SSH", enter the IP address of the AnotterKiosk and with a lot of luck you can log into the machine. 
We can then troubleshoot from there.

**Comment by chrisdlees** [comment]
I'm about 95 percent sure I know the problem. 

Simply adding nouveau as a kernel extension doesn't work, make sure to add the flags `i915.modeset=0 nouveau.modeline=1` has been added to the end of one of your init lines in GRUB (as in, add it to the end of your boot option's command)

Also make sure initramfs was configured properly, you should have added the options to enable nouveau and to disable the intel/i915 drivers to your /etc/dracut.conf file prior to rebuilding the kernel.

It's generally an either or situation, so pressing `e` instead of `enter` in GRUB and adding those flags should just work.

_**BUT MOST IMPORTANTLY, IF YOU PRESS `ctrl`+`alt`+`any of the first 7 "f-keys"` IN LINUX, IT WILL TAKE YOU TO A BLANK LOGIN TERMINAL ON A DIFFERENT TTY, EVEN IF THE SYSTEM APPEARS TO HAVE COMPLETELY HUNG OR X IS FREAKING OUT. TRY IT ANYTIME, ITS INSTANTANEOUS, AND THE X SESSION GENERALLY RUNS ON F7, SO YOU CAN QUICKLY CHANGE BACK. LINUX BASICALLY STARTS UP 7 DIFFERENT TERMINALS AT BOOTTIME, X IS RUNNING ON TTY7/f7, AND THE OTHER SESSIONS ARE ALWAYS THERE IF YOU NEED THEM**_

Sorry for the all caps, but I felt it was super important to give this helpful info. SSH is definitely not the way to go AT ALL in this situation lol. You can get the logs, or kill X and then restart it  from one of the other TTYs. 

It saved me when I was young and learning Linux.

**Comment by PPPDUD** [comment]
Do you mean the video outputs provided by the motherboard on the back of my
PC? If so, I'm already connected to them.

**Comment by Manawyrm** [comment]
> Do you mean the video outputs provided by the motherboard on the back of my PC? If so, I'm already connected to them.

Wait... You have a Nvidia 2080 and you're connnected to your mainboards output instead of the Nvidia GPU?!
You definitely shouldn't do that, not even on Windows. That looses a lot of performance (in games, etc.) and causes several other disadvantages.

... switch your monitor to the Nvidia then, play some games on Windows and enjoy tons of free performance? :laughing:

**Comment by PPPDUD** [comment]
> > Do you mean the video outputs provided by the motherboard on the back of my PC? If so, I'm already connected to them.
> 
> Wait... You have a Nvidia 2060 and you're connected to your mainboards output instead of the Nvidia GPU?! You definitely shouldn't do that, not even on Windows. That looses a lot of performance (in games, etc.) and causes several other disadvantages.
> 
> ... switch your monitor to the Nvidia then, play some games on Windows and enjoy tons of free performance? 😆

Hmm.. never heard of the performance impact before. Can you send me some links that support this theory?

**Comment by chrisdlees** [comment]
@Manawyrm I feel bad for making so many assumptions, I hope you can forgive my dick-ish-ness...
But on a seperate note, have you considered a debug flag for pre-boot time? Maybe even have the flag be chosen by the admin, to be set in a config file, thereby making it so a member of the public couldn't just google it.
I dunno, just spitballing.... 
Unrelated, are you taking pull requests/do you have a roadmap or anything? I kinda feel like I should contribute as penance for being a jerk haha

**Comment by Manawyrm** [comment]
> So I guess the question is now just about if you take pulls.

Sorry, I didn't see the edit back then. I mostly read GitHub through the email notifications (which don't include the edits).

This is an interesting idea, not something I need on my boxes (mostly because they don't even have a keyboard in the field and I use SSH/tunneling to access them) -- but I would be happy about such a pull request. It sounds useful -- and yes, I would gladly accept something like that.

**Comment by Manawyrm** [comment]
This should be fixed with the 0.5.0 release.
